Update packets to latest spec
SSL-A-Team/software-communication pull request #5
Opened 2022-09-25 22:30 UTC by barulicm

Updated the packet structs to match the current spec doc as I start implementing the radio bridge node.

Note: enum name prefixes (ie. `DT_*`) are to help avoid name conflicts with common macros / global names. We're mulling over converting these headers to C++ to get better name spacing tools.

2022-09-26 02:16 UTC, guyfleeman requested changes
looks good overall, if need to move the discussion about KickRequest to the google doc, we can

2022-09-26 02:16 UTC, guyfleeman commented on ateam-common-packets/include/basic_control.h
> +    uint8_t kick_request;
Should this type be KickRequest_t? Or are you using it to constrain the type size?

2022-09-26 02:16 UTC, guyfleeman commented on ateam-common-packets/include/basic_control.h
> +typedef enum KickRequest {
I think we should add a type here to clarifiy ready vs discahrage? Maybe KR_ARMED, KR_DISABLE? KR_ARM would keep the device charged, but no kick action would occur ever. KR_DISABLE would initiate a discharge.

2022-09-26 02:16 UTC, guyfleeman commented on ateam-common-packets/include/basic_telemetry.h
> +    float kicker_charge_level;
nit: can annotate this unit as volts

2022-09-26 02:16 UTC, guyfleeman commented on ateam-common-packets/include/hello_data.h
> +    TeamColor color;
unfamiliar with C++ overlap here but should this be TeamColor_t?

2022-09-26 04:50 UTC, guyfleeman approved these changes

2022-09-26 04:50 UTC, guyfleeman commented
do you wanna take a stab at adding the Rust bind gen support, or do you want me to push that up?

2022-09-26 05:35 UTC, barulicm commented
Does each header need a new builder setup, or can I just add more `.header(...)` calls to the one in build.rs?

2022-09-26 16:30 UTC, guyfleeman commented
Looks like you can add more header() chained calls. https://docs.rs/bindgen/latest/bindgen/struct.Builder.html

2022-09-27 04:07 UTC, guyfleeman commented
looks like all updates were captured by CI and layout tests are passing

2022-09-27 04:59 UTC, merged